course_name = "自动控制实践 A"
repo_type = "normal"
course_code = "AUTO3002A"

description = """
该课程有配套的课程设计（2024 年秋季学期起改名为“实验”）：[自动控制实践 A 实验](https://hoa.moe/docs/junior-autumn/auto3016/)，独立设课，1.5 学分，40 学时。

本课程涵盖三部分内容，以第一块内容为最重：

1. 电机驱动与拖动
2. 简单的电力电子技术（PWM）
3. 传感与测量元件
"""

[[lecturers]]
name = "隆志力"

[[lecturers.reviews]]
content = """
（21 级、22 级情况）
**授课风格**：稍显含糊，车轱辘话较多；课件内容较丰富，有别学校课件截下来的内容，不过画质较差，而且比较乱，不适合直接做笔记。
**听课建议**：基本忠于 PPT（不会自由发挥），由于车轱辘话较多，知识讲解得比较抽象，上课不易听懂，课后要多花时间。
"""

[[lecturers]]
name = "李建刚"

[[lecturers.reviews]]
content = """
（21 级、22 级情况）
**授课风格**：语速很快（因为学时有限、内容又多，到后面会快到起飞）、逻辑较清晰（到后面由于速度快变得不清晰）、答疑有耐心、板书不好看、语气词较多（到后程语速极快，但信噪比极低）、课件较美观（但是由于摘选自外校课件，有较多符号的冲突，时有逻辑不连贯）。
**听课建议**：因为上课节奏较快，上课只求听懂大概即可（更有可能是听不懂），但课后务必（参考前人资料）整理笔记！！！
"""


[[sections]]
title = "教材与参考资料"

[[sections.items]]
content = """
传统电机学教材，可以看里面的直流电机、变压器、异步电机和同步电机：

- **电机学**（戈宝军, 梁艳萍, 温嘉斌 / 中国电力出版社 / 第三版 / textbook）
- **电机学**（汤蕴璆 / 机械工业出版社 / 第 5 版 / textbook）
- **电机与拖动**（孙建忠、刘凤春等 / 机械工业出版社 / 第 4 版 / textbook）
- **步进电机应用技术**（[日]坂本正文 (王自强译) / 科学出版社 / 2010年版 / textbook）
- **电力电子技术**（王兆安等 / 机械工业出版社 / 第 5 版 / textbook）
- [电机学（哈尔滨理工大学）- Bilibili](https://www.bilibili.com/video/BV1cx411Z76w)：戈宝军教材配套网课
- （一些奇怪的论坛里的 pdf，找到后放上来，部分参考书资源已传至网盘）

本门课对电力电子技术要求很低。如果大家想拓展 ~~(学电气的专业课)~~ ，可以参考：

- **Fundamental of power electronics**（Erickson / Springer / 3rd ed. / textbook）
- **自动控制元件及线路**（梅晓榕 / 科学出版社 / 第五版 / textbook）
- [傅旻帆个人主页 - Bilibili](https://space.bilibili.com/519909115)：电力电子技术拓展资源
- [西瓜粥西瓜粥个人主页 - Bilibili](https://space.bilibili.com/287344644)：电力电子技术拓展资源
（请大家量力而行，学有余力再去看拓展提高的内容！）
"""

[[sections]]
title = "关于考试"

[[sections.items]]
content = """
- 题量较大，但是含有大量往年题。对于做过往年题的同学来说，完卷并不困难，甚至有较多时间检查。
- 有少数题目不太严谨，不要因为这个影响答题。
- 仅做往年题而不理解概念的后果，就是对于往年题之外的题目无从下手。所以这门课虽说挂科率不高，但考高分的也少。
- 所以，往年题只供大家参考，只靠通过刷往年考试题来获取高分或者保证不挂科是**不可取的**。而且往年题有许多题目并无答案，需要理解并且与同学讨论来得出答案。**希望大家认真复习，把基本概念、方法掌握扎实。**
"""
author = { name = "Oliver Wu", link = "https://www.github.com/OliverWu515", date = "2024-02" }

[[sections.items]]
content = """
24 秋，对于自控实践 A 这门课考试的复习，最重要的是清楚地知道**我们是自动化专业而不是电气专业**，由于电气专业同步上电机学，和我们的部分内容有相关性，且是同时考试，导致部分同学因为看到电气同学的复习内容而对我们的考试过于担忧，这不仅是 22 级的现象，21 级也有类似现象。通过分析近两年的考题便可发现，我们的考试内容重点和电气的电机学有很大不同，因此不要盲目焦虑。例如有刷直流电机部分的计算是重点，需掌握发电机和电动机的基本平衡方程以及机械特性；而异步电机部分对于功率的计算有一定要求，但归算部分没有要求。因此我在复习的时候直接跳过了变压器和异步电机的归算，直接记归算结果（等效电路）。

24 秋的考试相比 23 年，后面的计算题和综合题（就是复杂一些的计算题）几乎没有变化，但是每道计算题和往年相比都会有细微的差别，导致实际上每道题都需要经过自己的思考。因此**仅仅背题而不理解知识点是完全不够的**。我上传了往年题以及章节题目的详细解析，希望其中的思考过程可以帮助大家更好地理解知识点。（与其他同学进行过多次讨论校对，但如果仍有错误欢迎修改，也欢迎补充更多的解题思路及技巧）

此外，前面的选择题、填空题、简答题的比重有所上升，所包含的知识点范围也很广，复习的面面俱到确实难度较大。推荐同学们可以参考 notes 文件夹下 wjd 学长 [Oliver Wu](https://github.com/OliverWu515) 的笔记，他对课程中出现的每个知识点都有仔细地思考和详尽的解释，对于复习时理解知识点有很大的帮助。

24 秋考试可以携带计算器。
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-12" }

[[sections]]
title = "关于实验"

[[sections.items]]
content = "自控实践 A 的课内实验内容较为简单，每个实验的内容都很少，可以速通，但是最后给分的情况比较玄妙。"
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2025-01" }

[[sections]]
title = "课程安排"

[[sections.items]]
content = """
学时安排表（21级）
| 授课教师 | 授课内容 | 学时安排 | 建议 |
| :--- | :--- | :--- | :--- |
| 隆志力 | 绪论 | 2 | 了解即可。 |
| 隆志力 | 磁路基础 | 2 | 重要！磁量的关系、磁路定律要很清楚，<br>变压器和交流电机中经常用到。 |
| 隆志力 | 直流电机的结构和工作原理 | 2 | 结构要认识（不用细到绕法这些，只要知道每个部件名称和属于定子还是转子）、<br>工作原理比较好理解，重点是换向器和电刷，简单描述即可。 |
| 隆志力 | 直流电机的磁场、电枢反应与换向 | 2 | 理解，重在知道结果，不是重点。 |
| 隆志力 | 直流电机基本方程、机械特性、调节特性 | 2 | 很重要，需要记忆几乎每个公式！<br>数形结合是很重要的方法！结合图形分析事半功倍！ |
| 隆志力 | 直流电机的调速运行 | 2 | 很重要，需要结合图形记忆调速方式的特点！ |
| 隆志力 | 直流电机的四象限运行（工作状态） | 2 | 很重要，需要结合图形记忆每个象限、曲线的不同阶段对应的工作状态！ |
| 隆志力 | 电力电子技术概述 | 2 | 理解，主要关注器件分类、工作原理、适用范围。 |
| 隆志力 | PWM | 2 | 很重要，需要理解一个周期PWM元件上的电流流向、<br>导通关断与否以及元件的作用。 |
| 隆志力 | 变压器 | 2 | 很重要，学时很少，要记忆的东西却很多。<br>重点在负载运行和空载运行的基本方程和T形等效电路。<br>笔记文件夹里的笔记整理得很清楚。 |
| 李建刚 | 课程概述 | 1 | 了解即可。 |
| 李建刚 | 步进电机的结构与工作原理 | 1 | 重要。理解“错齿是使步进电机运动的根本原因”。<br>关于齿数的计算，反应式和混合式其实是有不同的。<br>但是一般按照反应式的公式计算。 |
| 李建刚 | 步进电机的静态特性、动态特性与驱动 | 3 | 重要。静态特性主要是矩角特性，<br>动态特性主要是从矩角特性出发用合成法来分析启动特性（图解特别重要），以及矩频特性。<br>驱动以细分驱动为主。 |
| 李建刚 | 交流电机概述 | 2 | 这节课让大家对异步电机和同步电机的结构和工作原理有基本的认识。<br>但是详细的分析还需后面仔细学习。 |
| 李建刚 | 无刷直流电机与交流伺服电机 | 5 | 讲得最细致的部分，但其实原理相对比较简单，<br>重点理解六步换向和 Clark-Park/d-q 变换，<br>理解如何将伺服电机的驱动变得像有刷直流那样简单。 |
| 李建刚 | 测量元件、旋转变压器、感应同步器、编码器、光栅 | 3 | 由于学时剩余很少，讲课速度开始进入倍速模式。<br>大家从这里开始只要尽量听明白就行，笔记课后再做。 |
| 李建刚 | 交流绕组的基本原理，三相异步电机的原理及结构 | 2 | 是重点，也是难点！！但是学时比较少。<br>旋转磁场理解起来比较困难。<br>详见文件中的异步电机笔记。 |
| 李建刚 | 三相异步电机的等效电路及运行分析，机械特性和调速运行 | 约2.5 | 是重点，也是难点！！但是你没看错，2学时结束了。<br>等效的流程：电路模型 -> 频率归算 -> 绕组归算。<br>**异步电机可以看成“会动的变压器”！**<br>详见 notes 文件夹下异步电机的笔记。<br>考试基本是定性分析，定量分析（计算题）要求不高，难度不超过作业题。 |
| 李建刚 | 单相异步电机的等效电路及运行分析 | 约0.5 | 需要理解单相异步电机的启动，有小题。 |
| 李建刚 | 小功率同步电机 | 0 | 没时间了，没讲，考试不涉及。 |
"""
author = { name = "Oliver Wu", link = "https://www.github.com/OliverWu515", date = "2024-02" }

[[sections]]
title = "习题答案与注意事项"

[[sections.items]]
content = """
- [《自动控制元件》复习笔记及习题答案 - Bilibili 专栏](https://www.bilibili.com/read/cv19892484/)
- [《自动控制元件》期末总结及课后习题答案 - Bilibili 专栏](https://www.bilibili.com/read/cv22652100)

> [!NOTE]
> 1. 以上两篇专栏为民间整理，不能保证完全正确，阅读时自行辨别正误。
> 2. 本仓库 materials 文件夹下的《自动控制元件及线路课后题答案（百度文库）》与《自动控制元件习题资料》系从网上下载，部分习题与老师布置的课后作业相同，可作补充，但是答案不一定正确，仅供参考。
"""
